### ISSUE TITLE
strip ANSI codes from /review output

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#202]
@brianyu28 now that the CLI is POSTing output that might have ANSI codes, what's the easiest way to strip those codes before rendering `/review` at 
https://github.com/cs50/help50/blob/master/application.py#L86 since `inputs` is currently coming directly from the model? Can we first filter `inputs.script` with a line like https://github.com/cs50/help50/blob/master/application.py#L46?

We _could_ strip the ANSI codes before INSERTing `script` in the first place, but feels ideal to preserve original inputs.

**Comment by brianyu28** [comment]
Could certainly iterate over all unreviewed rows of `inputs` in `model.py` and strip the ANSI codes from each.

Hm, stripping the codes before INSERTing would avoid having to re-process each input every time we want to view `/review`, though. It also would functionally preserve inputs just as well as it did previously, since we haven't been storing ANSI codes in our database thus far.

**Comment by dmalan** [comment]
I think, as a matter of principle, we should probably store original input,
especially if we need to chase down some future bug. Is there a way to
define a filter on a model for a particular field? /review is only rarely
accessed so the repeated work doesn't sound worrisome.

**Comment by brianyu28** [comment]
Sounds good, will look into the SQLAlchemy documentation to see if I can find anything.

**Comment by dmalan** [comment]
https://github.com/cs50/help50/commit/084eef41ec59e28c09aaf65c95946a5b7004a02b!

Source: http://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html#using-descriptors-and-hybrids
