### ISSUE TITLE
unknown escape sequence error

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/help50#237]
If there's a space between the `\` and the character meant to be escaped (`'\ n'` or `'\ t'` for example), you'll get an unknown escape sequence error, per the below sample.

```
water.c:9:21: error: unknown escape sequence '\ ' [-Werror,-Wunknown-escape-sequence]
printf("bottles: %i \ n", shower);
                    ^~
1 error generated.
make: *** [water] Error 1
```

**Comment by dmalan** [comment]
Good one! Want to propose a PR? :)

**Comment by curiouskiwi** [comment]
Something like?

A backslash `'\'` tells the compiler to expect an escape sequence, which allows you to easily print non-character codes, such as newlines or tabs.    
[check if char after the space is an `n`.] 
Looks like you meant  to add a new line.  Try`'\n'` with no extra space.
[else:]
Make sure you have no space after the `'\'`.

**Comment by dmalan** [comment]
Thanks! https://github.com/cs50/help50/commit/8f36255c2643e9773eba4729a53789d20f9d3fb5

**Comment by dmalan** [comment]
@brianyu28, thoughts on how easily we could extract the substring on `lines[1]` starting with the character above the `^` on `lines[2]`? Because the symbol above the caret isn't a variable, I don't _think_ we can extract it atm with `caret_extract`?

https://github.com/cs50/help50/commit/8f36255c2643e9773eba4729a53789d20f9d3fb5#diff-cd13aa89269bf847f295b97bb783aef9R757
