### ISSUE TITLE
when copy/pasting script from /review, newlines not preserved when pasted

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#32]
Does row in DB perhaps have `\r`? Should we force to `\n` when rendering for copy/paste convenience?

<img width="1195" alt="screen shot 2016-09-06 at 12 04 12 am" src="https://cloud.githubusercontent.com/assets/788678/18261406/98c91774-73c5-11e6-8c68-dd5416f6569f.png">

<img width="1024" alt="screen shot 2016-09-06 at 12 04 18 am" src="https://cloud.githubusercontent.com/assets/788678/18261407/98cb48d2-73c5-11e6-8695-a81c0590ad5c.png">

**Comment by brianyu28** [comment]
Don't think this is a db issue. Right now the `td` cells have a `white-space: pre-line` CSS attribute attached to it, so that the new lines appear in the table. Seems that `pre-line` in general doesn't preserve newlines on copy-paste, I had the same issue when just trying to copy the text out of a sample HTML document like:

```
<html>
    <body>
        <p style="white-space:pre-line;">
        First line.
        Second line.
        Third line.
        </p>
    </body>
</html>
```

I'll explore possible solutions.

**Comment by dmalan** [comment]
Can probably just use <pre/>?

**Comment by brianyu28** [comment]
Just tested it, that works. Will submit a PR.
