### ISSUE TITLE
start including comments atop matchers?

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#5]
Brian, rather than include sample files and such, which feels like it'll become unwieldy to maintain longer term, especially since some commands will require creating files, etc. in order to simulate... shall we simply start prefixing matchers with multi-line examples of output that they match? E.g., rather than just do

```
# undefined reference
if ...
```

we can instead do

```
# /tmp/ccOsNy8L.o: In function `main':
# 3.c:(.text+0xe): undefined reference to `get_string'
# collect2: error: ld returned 1 exit status
# make: *** [3] Error 1
if ...
```

? Afraid I'm already starting to forget the context for some of the matchers! 

Up for tweaking our comments accordingly if this feels compelling?

**Comment by brianyu28** [comment]
I do think that this is probably a much more sustainable solution long term rather than the example files, would be happy to work on that.

For cases that are meant to match multiple different error outputs (for instance, the matcher from  https://github.com/cs50/help50/pull/4 earlier tonight is meant to match two different types of mistakes that happen to share the same error message; and the `rm` matcher which matches both the `empty` and the not empty version of the file), should we just include multiple multi-line examples atop each matcher?

**Comment by dmalan** [comment]
Okay, sounds good. I think so, let's see if that proves manageable. Let's just separate disparate examples with a blank `#` line. And better yet, rather than

```
# /tmp/ccOsNy8L.o: In function `main':
# 3.c:(.text+0xe): undefined reference to `get_string'
# collect2: error: ld returned 1 exit status
# make: *** [3] Error 1
if ...
```

why don't we go one step further to jog our memories and do

```
# $ make foo
# /tmp/ccOsNy8L.o: In function `main':
# 3.c:(.text+0xe): undefined reference to `get_string'
# collect2: error: ld returned 1 exit status
# make: *** [3] Error 1
if ...
```

so that we remember the command executed, genericizing the command to just `foo` or such when applicable.

**Comment by brianyu28** [comment]
All helpers have been updated to use this comment format. Should I remove the `examples/` directory at this point to avoid confusion?

**Comment by dmalan** [comment]
Aok!
