### ISSUE TITLE
show only a subset of input along with output?

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#51]
So I've been thinking about whether there's a better way to display `help50`'s output. At the moment, we display the entirety of its input, below which, in yellow, is its output. 

But I wonder if we should start showing only the first _n_ lines of input, where _n_ - 1 is the (last) line we matched. That'd shorten total output in many cases. And we could also start to highlight substrings in the input (e.g., filenames, line numbers, portions of error messages). 

Separately, we currently output lines of output, adding `\n`s irrespective of screen width. Am thinking we should start outputting "paragraphs" instead and let them wrap naturally.

Thoughts? Can we produce better output?

**Comment by brianyu28** [comment]
Alternatively, we could adopt the web interface's model, which only displays the lines of code that we output in the `before` part of the `(before, after)` return value of any `help` function?

When I input:

```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    test.c  -lcs50 -lm -o test
test.c:6:8: error: expected '(' after 'if'
    if x == 28
       ^
1 error generated.
make: *** [test] Error 1
```

into the web interface, the resulting page I get just has the single line:

```
test.c:6:8: error: expected '(' after 'if'
```

followed by the `after` advice. I think there's definitely pedagogical value in showing less input, so that students can better link the semantics of the error message itself with `help50`'s interpretation and rely on it less in the future.

However, right now, if compiling a program results in three errors, and `help50` only catches the third one, then the command line interface would show all three errors, while the web interface would only show the third one. Is there a preferable option here?

**Comment by dmalan** [comment]
Hm, something tells me we should show lines 0 through _n_ - 1, lest we hide the actual source of a problem (that we just haven't happened to match on yet)? 

Rather than have a matcher return `(before, after)`, should we instead have it return `(n, help)`, where `n` is the number of lines matched and `help` is just a renaming of `after`? 

I was hoping there might be a cleaner way, whereby we could just pass each helper the whole array but rely on an internal cursor, but seems https://docs.python.org/2/library/stdtypes.html#iterator-types, at least, doesn't offer much more than `next()`.

**Comment by brianyu28** [comment]
Okay, I agree, that makes sense. `(n, help)` seems like a good way to deal with this. For cases like:

```
foo.c:5:15: error: expected ';' at end of declaration
    int x = 28
              ^
              ;
1 error generated.
make: *** [foo] Error 1
```

I would imagine we would want `n` to be 4 (so as to capture `clang`'s own recommendations in addition to ours). Right now most of our matchers for cases like this only check for the existence of one line, and return just `lines[0:1]`.

**Comment by dmalan** [comment]
Agreed, though rather than blindly just return `4`, we should probably check that the only thing on `lines[2]` is `\s*^` and the only thing on `lines[3]` is `\s*;`?

Want to take a stab at transitioning to this?

**Comment by brianyu28** [comment]
Will do.
